networks:
  1panel-network:
    external: true

services:
  beszel-agent:
    image: henrygd/beszel-agent:0.10.2
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    network_mode: ${NETWORK_MODE:-host}
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Shanghai
      - LOG_LEVEL=info
      - PORT=${PANEL_APP_PORT_HTTP:-45876}
