networks:
  1panel-network:
    external: true

services:
  linkding:
    image: sissbruecker/linkding:1.41.0-plus
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - ${PANEL_APP_PORT_HTTP}:9090
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${LINKDING_ROOT_PATH}/data:/etc/linkding/data
    environment:
      - LD_SERVER_PORT=9090
      - LD_DB_ENGINE=postgres
      - HTTP_PROXY=${ALL_PROXY}
      - HTTPS_PROXY=${ALL_PROXY}
