networks:
  1panel-network:
    external: true

services:
  nezha-dash:
    image: hamster1963/nezha-dash:v2.9.2
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    environment:
      - DefaultLocale=zh
      - ForceShowAllServers=false
      - NEXT_PUBLIC_NezhaFetchInterval=5000
      - NEXT_PUBLIC_ShowFlag=true
      - NEXT_PUBLIC_DisableCartoon=false
      - NEXT_PUBLIC_ShowTag=true
      - NEXT_PUBLIC_ShowNetTransfer=false
      - NEXT_PUBLIC_ForceUseSvgFlag=false
      - NEXT_PUBLIC_CustomLogo=https://nezha-cf.buycoffee.top/apple-touch-icon.png
      - NEXT_PUBLIC_CustomTitle=NezhaDash
      - NEXT_PUBLIC_CustomDescription=NezhaDash is a dashboard for Nezha.
