networks:
  1panel-network:
    external: true

services:
  dpanel:
    image: dpanel/dpanel:1.2.5-lite
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${DPANEL_ROOT_PATH}/data:/dpanel
      - ${DPANEL_ROOT_PATH}/compose:/dpanel/compose
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_NAME=${CONTAINER_NAME}
  dpanel-plugin-explorer:
    image: alpine:latest
    container_name: dpanel-plugin-explorer
    restart: unless-stopped
    privileged: true
    pid: host
    command: [ "sh", "-c", "tail -f /dev/null" ]
