networks:
  1panel-network:
    external: true

services:
  windows:
    image: dockurr/windows:4.21
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    stop_grace_period: 2m
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8006
      - ${PANEL_APP_PORT_REMOTE}:3389/tcp
      - ${PANEL_APP_PORT_REMOTE}:3389/udp
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/dri:/dev/dri
      # - /dev/nvidia0:/dev/nvidia0
      # - /dev/nvidiactl:/dev/nvidiactl
      # - /dev/nvidia-modeset:/dev/nvidia-modeset
      # - /dev/nvidia-nvswitchctl:/dev/nvidia-nvswitchctl
      # - /dev/nvidia-uvm:/dev/nvidia-uvm
      # - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      # - /dev/video11:/dev/video11
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${WINDOWS_STORAGE_ROOT_PATH}/storage:/storage
      - ${WINDOWS_SHARE_ROOT_PATH}/share:/data
      - ${WINDOWS_OEM_ROOT_PATH}/oem:/oem
    environment:
      - REGION=en-US
      - KEYBOARD=en-US
      - VERSION=${VERSION}
