networks:
  1panel-network:
    external: true

services:
  stream-rec-frontend:
    image: streamrec/stream-rec-front:v0.7.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:15275
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
