version: "3.8"

networks:
  1panel-network:
    external: true

services:
  stream-rec-backend:
    image: streamrec/stream-rec:v0.6.9
    container_name: ${CONTAINER_NAME}-backend
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_API}:12555
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${STREAM_REC_ROOT_PATH}/records:/opt/records
      - ${STREAM_REC_ROOT_PATH}/download:/download
    environment:
      - LOG_LEVEL=INFO
      - DB_PATH=/opt/records
      - DOWNLOAD_PATH=/download

  stream-rec-frontend:
    depends_on:
      - stream-rec-backend
    image: streamrec/stream-rec-front:v0.6.9
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:15275
    env_file:
      - /etc/1panel/envs/global.env
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
